name = "cyd-video-converter"
compatibility_date = "2026-01-29"

[site]
bucket = "."

[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Embedder-Policy = "require-corp"
Cross-Origin-Opener-Policy = "same-origin"
